Famelo:
  TranslationHelper:
#    autoCreateTranslations: false
#    autoCreationWhitelist:
#      - My.Package
    debugWrapTranslations: false

TYPO3:
  Flow:
    log:
      # Settings for TYPO3 Flow's default loggers
      translationLogger:
        logger: TYPO3\Flow\Log\Logger
        backend: TYPO3\Flow\Log\Backend\FileBackend
        backendOptions:
           logFileURL: '%FLOW_PATH_DATA%Logs/Translation.log'
           createParentDirectories: TRUE
           severityThreshold: '%LOG_INFO%'
           maximumLogFileSize: 10485760
           logFilesToKeep: 1
           logMessageOrigin: FALSE